"""initial_schema

Revision ID: d7faff4526cc
Revises: 
Create Date: 2025-12-20 15:07:03.390240
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7faff4526cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('requests_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_length', sa.Integer(), nullable=False),
    sa.Column('difficulty_tag', sa.Enum('SIMPLE', 'MEDIUM', 'COMPLEX', name='difficulty_tag_enum'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('baseline_cost', sa.Float(), nullable=False, comment='Cost if GPT-4o/Gemini Pro was used'),
    sa.Column('cost_saved', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_log_api_key_id'), 'requests_log', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_requests_log_difficulty_tag'), 'requests_log', ['difficulty_tag'], unique=False)
    op.create_index(op.f('ix_requests_log_model_used'), 'requests_log', ['model_used'], unique=False)
    op.create_index(op.f('ix_requests_log_timestamp'), 'requests_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_log_timestamp'), table_name='requests_log')
    op.drop_index(op.f('ix_requests_log_model_used'), table_name='requests_log')
    op.drop_index(op.f('ix_requests_log_difficulty_tag'), table_name='requests_log')
    op.drop_index(op.f('ix_requests_log_api_key_id'), table_name='requests_log')
    op.drop_table('requests_log')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
